language: node_js
node_js:
  - "7"

addons:
  code_climate:
    repo_token: 4f5e844017b673d26e824bc8f636dc8ad820f324da8286c64d77b34384e4b7f6

script: make lint test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < testcoverage/lcov.info
